### ISSUE TITLE
1.12.2 crash on server

### ISSUE THREAD

**Issue by drstorm81** [Aroma1997/BetterChests#93]
Crash while starting-up server. 

Time: 12/19/17 2:57 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/gui/Gui
        at aroma1997.betterchests.filter.ItemFilter.getInventoryFor(ItemFilter.java:34)
        at aroma1997.betterchests.filter.ItemFilter.func_77667_c(ItemFilter.java:68)
        at net.minecraft.item.Item.func_77657_g(Item.java:292)
        at net.minecraft.item.Item.func_77653_i(Item.java:362)
        at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
        at net.minecraft.item.ItemStack.func_151000_E(ItemStack.java:1047)
        at net.minecraft.stats.StatList.func_75925_c(StatList.java:201)
        at net.minecraft.stats.StatList.reinit(StatList.java:346)
        at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:552)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
        at com.google.common.eventbus.EventBus.post(EventBus.java:217)
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
        at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:900)
        at net.minecraftforge.registries.GameData.freezeData(GameData.java:233)
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:728)
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:336)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.Gui
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 30 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer toughasnails.asm.transformer.CropDecayTransformer@31f20c9f from coremod TANLoadingPlugin
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
        ... 32 more
Caused by: java.lang.NullPointerException

**Comment by Aroma1997** [comment]
Should be fixed in build 55. If it isn't, please let me know.
